/**
 * Generated by scripts/generate-icons.mjs — do not edit by hand.
 *
 * The tray icon is embedded rather than read from disk so it works identically
 * in development and inside the packaged asar, with no path resolution.
 */

/** 64x64 source, downscaled by the OS to the tray's real size. */
export const TRAY_ICON_64 =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAEklEQVR42mNgGAWjYBSMAggAAAQQAAGvRYgsAAAAAElFTkSuQmCC'

/** 32x32 source for high-DPI trays. */
export const TRAY_ICON_32 =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAnElEQVR42mNgGAWjYBSMAiKAiKql5YBYzCUkI+M35fHjiGX//1vnr1pFdwfImoeGgiyHYbo7AhT0yA4AYZfGY8dAITNgoQDCoGihuyNgaWHAHIGcIAeVI+iaMAfUAQMaBQOaCInJhiA1uDBFjiSmIEIPGWyY7LqEmKKYkOUgDDKHZpURSByf5VRJK4SCECSPKw2MNmZGwSgYBYQAALPiHzZULkLkAAAAAElFTkSuQmCC'
